### ISSUE TITLE
Is there a plan to support docker?

### ISSUE THREAD

**Issue by musnow** [RedL0tus/trigger#1]

**Comment by RedL0tus** [comment]
Sorry for replying this late. I don't quite understand how to use it with Docker. Could you please give me an example of this type of usage?

中文也可以的。

**Comment by RedL0tus** [comment]
Sorry, I misunderstood it. Do you mean to support webhooks from Docker Hub?

I’m wokring on it, but the problem is there is no way to identify a request from Docker Hub rather than the NewRelic ID in the header (their User Agent is "python-requests"), and there is no way to actually validate the payload. But I’ll try.

**Comment by musnow** [comment]
我的意思是放到docker里面运行，
制作一个Dockerfile是不难的，希望得到支持
如果您不熟悉的docker 我可以提供一个pr？

当然，支持Docker Hub是一个有趣的方向，期待你的成果

**Comment by RedL0tus** [comment]
我主要是不太明白这个东西放到 Docker 里面之后要怎么使用，它本身的目的就在于跟别的程序互动，放到容器里有点像是自找麻烦（这话可能有点难听）。而且把它容器化的优点也不是很明显，Release 里面的二进制已经是静态链接过的了，不需要任何依赖就能运行，除了占用一个端口、读取一个配置文件和用 shell 执行脚本以外也不会做别的什么事情了，体积也只有 2MB；如果容器里需要使用的话直接把二进制复制进去也就行了。

我确实不是很熟悉 Docker 相关的流程，没有什么相关的经验，我上面说的只是根据我的理解来说的（可能有错）。对它的支持是可以做的，如果能有相关 PR 的话自然是极好的，或者过几天我看看能怎么搞这个支持。

至于 Docker Hub 的话，它的 webhook 实现很微妙（没有 event 概念，除了 NewRelic 这个统计服务的 ID 没有可供识别的 HTTP 头，验证 Payload 有效性的方式也很微妙），我现在在改 https://github.com/RedL0tus/rifling 为支持它做准备。将来可能还会去支持 Transifex 之类的平台的 webhook。

**Comment by musnow** [comment]
https://gist.github.com/musnow/120f776de7082f0aaba59266f3f239ba
这里有个简单的demo，
`docker build -t trigger:latest .`
build镜像之后可以使用run来挂载目录定义config
`docker run --volume $PWD:/app trigger trigger --help`
trigger 的端口可以使用nginx等反代出去。

**Comment by RedL0tus** [comment]
刚刚添加了 Dockerfile，能麻烦帮忙检查以下有什么问题吗。

确认没问题之后我去配置 Docker Hub 整合并更新 README。

**Comment by musnow** [comment]
我觉得没什么问题，使用应该没有逻辑问题，
可以先上线，有人反馈可以改的嘛~

**Comment by RedL0tus** [comment]
好了，推上了 https://cloud.docker.com/repository/docker/kaymw/trigger
